/* eslint-disable */
import React, { useState, useEffect } from 'react';

const KineticEnergyHarvesting = () => {
  const [sensorsActive, setSensorsActive] = useState(false);
  const [currentWattage, setCurrentWattage] = useState(0); // Watts generated this second
  const [totalEnergy, setTotalEnergy] = useState(0); // kWh
  const [crowdBPM, setCrowdBPM] = useState(0);
  
  const [powerLog, setPowerLog] = useState([
    { id: 1, time: '20:00:00', type: 'SYS', msg: 'Piezoelectric grid initialized at Main Stage.' },
    { id: 2, time: '20:00:05', type: 'SYS', msg: 'Routing kinetic micro-grid directly to stage lighting array.' }
  ]);

  // Visualizer bars for the dance floor
  const [floorGrid, setFloorGrid] = useState(Array(16).fill(0));

  useEffect(() => {
    let loop;
    if (sensorsActive) {
      loop = setInterval(() => {
        // Simulate crowd jumping to the beat
        const beatDrop = Math.random() > 0.8; 
        const baseBpm = beatDrop ? 140 : 128;
        setCrowdBPM(prev => Math.floor(prev + (baseBpm - prev) * 0.2));

        // Generate wattage based on BPM
        const jumpForce = beatDrop ? (Math.random() * 2000 + 3000) : (Math.random() * 1000 + 1000); // 1kW to 5kW range
        setCurrentWattage(jumpForce);
        
        // Add to total pool (converting W*s to kWh roughly for visualization speed)
        setTotalEnergy(prev => prev + (jumpForce / 3600000) * 1000); 

        // Update floor grid visuals
        setFloorGrid(Array(16).fill(0).map(() => beatDrop ? Math.random() * 100 : Math.random() * 40));

      }, 500); // Poll every half second
    } else {
      setFloorGrid(Array(16).fill(0));
      setCurrentWattage(0);
      setCrowdBPM(0);
    }
    return () => clearInterval(loop);
  }, [sensorsActive]);

  const simulateBassDrop = () => {
    if (sensorsActive) {
      addLog('ACTION', 'BASS DROP DETECTED. Maximum kinetic compression on piezoelectric tiles.');
      setCurrentWattage(12450); // Massive spike
      setCrowdBPM(150);
      setFloorGrid(Array(16).fill(100)); // All lights maxed
      
      setTimeout(() => {
        addLog('SUCCESS', 'Harvested 12.4kW peak. Routing to primary laser array.');
      }, 500);
    }
  };

  const toggleSensors = () => {
    if (!sensorsActive) {
      setSensorsActive(true);
      addLog('SYS', 'Kinetic energy harvesting active. Grid synced with PA system.');
    } else {
      setSensorsActive(false);
      addLog('SYS', 'Harvesting paused. Reverting stage lighting to diesel generator.');
    }
  };

  const addLog = (type, msg) => {
    const now = new Date();
    const timeStr = `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}:${now.getSeconds().toString().padStart(2, '0')}.${Math.floor(Math.random()*999).toString().padStart(3,'0')}`;
    setPowerLog(prev => [{ id: Date.now()+Math.random(), time: timeStr, type, msg }, ...prev].slice(0, 6));
  };

  return (
    <div className="min-h-screen bg-[#070b19] flex items-center justify-center font-sans p-6 text-slate-300">
      
      <div className="max-w-7xl w-full grid grid-cols-1 lg:grid-cols-12 gap-8 items-start relative">
        
        {/* Left Side: Power Ops Command (Col span 7) */}
        <div className="lg:col-span-7 space-y-6">
          <div className="inline-block bg-yellow-900/40 text-yellow-400 border border-yellow-500/30 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-widest mb-2 flex items-center w-max">
            <span className="mr-2">⚡</span> Kinetic IoT Micro-Grid
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-white leading-tight">
            Piezoelectric Dance Floor <br/><span className="text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 to-amber-500">Energy Harvesting</span>.
          </h1>
          <p className="text-slate-400 text-sm leading-relaxed mb-6">
            Festivals consume massive amounts of grid power, while simultaneously, 50,000 people are expending kinetic energy jumping up and down. Eventra integrates directly with piezoelectric dance floors to solve this. The IoT dashboard tracks the exact wattage generated by the crowd's physical movement in real-time. This kinetic energy is instantly routed to power the stage's lighting and laser arrays, significantly reducing reliance on diesel generators while creating a gamified connection between the crowd and the production.
          </p>

          <div className="bg-[#0b1021] rounded-3xl p-6 border border-slate-800 shadow-xl relative overflow-hidden flex flex-col h-[400px]">
             
             <div className="flex justify-between items-center mb-6 border-b border-slate-800 pb-4">
               <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest flex items-center">
                 <span className="text-yellow-500 text-lg mr-2">🔋</span> Kinetic Power Inverter
               </h3>
               
               <div className="flex space-x-2">
                 <button 
                   onClick={toggleSensors}
                   className={`px-4 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest transition shadow-md flex items-center ${
                     sensorsActive ? 'bg-slate-800 text-slate-500 border border-slate-700' :
                     'bg-yellow-600 hover:bg-yellow-500 text-slate-900 shadow-[0_0_15px_rgba(202,138,4,0.4)]'
                   }`}
                 >
                   {sensorsActive ? 'Disconnect Grid' : 'Engage Harvesters'}
                 </button>
               </div>
             </div>

             <div className="grid grid-cols-2 gap-4 mb-6">
               
               {/* Live Output */}
               <div className={`p-4 rounded-xl border flex flex-col justify-center relative overflow-hidden transition-all duration-300 ${
                 currentWattage > 8000 ? 'bg-yellow-950/40 border-yellow-500/50 shadow-inner' : 'bg-slate-900 border-slate-800'
               }`}>
                 <span className="text-[10px] text-slate-500 font-bold uppercase tracking-widest block mb-2">Live Kinetic Output</span>
                 <div className="flex items-end">
                   <span className={`text-4xl font-black font-mono leading-none ${
                     currentWattage > 8000 ? 'text-yellow-400' : 'text-white'
                   }`}>
                     {currentWattage > 0 ? (currentWattage / 1000).toFixed(2) : '0.00'}
                   </span>
                   <span className="text-sm font-bold text-slate-600 ml-2 pb-1">kW</span>
                 </div>
                 
                 <div className="mt-3 w-full h-1 bg-slate-800 rounded-full overflow-hidden">
                   <div 
                     className={`h-full transition-all duration-300 ${currentWattage > 8000 ? 'bg-yellow-400' : 'bg-emerald-500'}`} 
                     style={{ width: `${Math.min(100, (currentWattage / 15000) * 100)}%` }}
                   ></div>
                 </div>
               </div>

               {/* Metrics */}
               <div className="p-3 rounded-xl border border-slate-800 bg-slate-900 relative overflow-hidden flex flex-col justify-center space-y-4">
                 
                 <div>
                   <div className="flex justify-between items-end mb-1">
                     <span className="text-[9px] text-slate-500 font-bold uppercase tracking-widest block">Total Yield (Session)</span>
                     <span className="text-xs font-mono font-bold text-emerald-400">{totalEnergy.toFixed(3)} kWh</span>
                   </div>
                 </div>

                 <div>
                   <div className="flex justify-between items-end mb-1">
                     <span className="text-[9px] text-slate-500 font-bold uppercase tracking-widest block">Crowd Sync (BPM)</span>
                     <span className="text-xs font-mono font-bold text-rose-400">{crowdBPM}</span>
                   </div>
                 </div>

               </div>

             </div>

             {/* System Log */}
             <div className="flex-1 bg-slate-950 rounded-xl border border-slate-800 p-4 font-mono text-[10px] overflow-hidden relative flex flex-col shadow-inner mt-auto">
               <span className="text-slate-500 uppercase font-bold tracking-widest block mb-2 border-b border-slate-800 pb-2 flex justify-between">
                 <span>Power Management Log</span>
                 {sensorsActive && <span className="text-yellow-400 animate-pulse">Harvesting...</span>}
               </span>
               
               <div className="flex-1 overflow-y-auto space-y-1.5 text-slate-400 pr-2">
                 {powerLog.map((log) => (
                   <div key={log.id} className="flex items-start animate-fade-in-up">
                     <span className="text-slate-600 mr-2 shrink-0">[{log.time}]</span>
                     <span className={
                       log.type === 'SUCCESS' ? 'text-emerald-400 font-bold' : 
                       log.type === 'ACTION' ? 'text-yellow-400 font-bold' : 'text-slate-400'
                     }>{log.msg}</span>
                   </div>
                 ))}
               </div>
             </div>

          </div>
        </div>

        {/* Right Side: Stage IMAG Screen Simulator (Col span 5) */}
        <div className="lg:col-span-5 flex justify-center pt-8 lg:pt-0">
          
          <div className="w-full max-w-[400px] flex flex-col items-center">
            
            {/* Massive Stage Screen Mockup */}
            <div className={`w-full rounded-[1rem] border-[4px] border-[#111] shadow-[0_0_50px_rgba(0,0,0,0.8)] relative flex flex-col h-[280px] overflow-hidden font-sans mb-6 transition-all duration-300 ${
              currentWattage > 8000 ? 'shadow-[0_0_80px_rgba(202,138,4,0.3)]' : ''
            }`}>
              
              <div className="absolute top-0 inset-x-0 p-2 text-center z-30 pointer-events-none bg-black/40 border-b border-white/10">
                <span className="text-[8px] font-black uppercase tracking-widest text-slate-400">
                  Main Stage Left IMAG
                </span>
              </div>

              <div className="flex-1 relative flex flex-col items-center justify-center bg-black overflow-hidden p-6">
                
                {/* Simulated Crowd Gamification Screen */}
                <div className="absolute inset-0 bg-gradient-to-t from-yellow-900/40 to-black z-0 pointer-events-none"></div>

                {sensorsActive ? (
                  <div className="relative z-10 w-full text-center flex flex-col items-center">
                    <span className="text-[10px] font-black uppercase tracking-widest text-yellow-500 mb-2 drop-shadow-md">
                      Crowd Power Meter
                    </span>
                    
                    {/* Massive Wattage Readout */}
                    <div className="flex items-end justify-center mb-6">
                      <span className={`text-6xl font-black font-mono leading-none transition-all duration-100 ${
                        currentWattage > 8000 ? 'text-white scale-110 drop-shadow-[0_0_15px_rgba(255,255,255,0.8)]' : 'text-slate-300'
                      }`}>
                        {(currentWattage / 1000).toFixed(1)}
                      </span>
                      <span className="text-xl font-bold text-yellow-500 ml-1 pb-1">kW</span>
                    </div>

                    {/* Circular Progress (Abstract) */}
                    <div className="w-full h-8 bg-slate-900/80 rounded-full border border-slate-700 overflow-hidden relative">
                      <div 
                        className={`absolute left-0 top-0 bottom-0 transition-all duration-[50ms] ${
                          currentWattage > 8000 ? 'bg-gradient-to-r from-yellow-400 to-white' : 'bg-gradient-to-r from-yellow-700 to-yellow-500'
                        }`}
                        style={{ width: `${Math.min(100, (currentWattage / 12000) * 100)}%` }}
                      ></div>
                    </div>
                    
                    <p className={`text-[8px] font-bold uppercase tracking-widest mt-4 transition-opacity ${
                      currentWattage > 8000 ? 'opacity-100 text-yellow-300 animate-pulse' : 'opacity-0'
                    }`}>
                      Powering Primary Lasers!
                    </p>
                  </div>
                ) : (
                  <div className="relative z-10 text-center opacity-30">
                    <span className="text-4xl block mb-2">🔌</span>
                    <p className="text-[10px] font-bold text-white uppercase tracking-widest">IMAG Standby</p>
                  </div>
                )}

              </div>
            </div>

            {/* Hardware Floor Controls (Simulating the physical tiles) */}
            <div className="w-full bg-slate-900 p-4 rounded-xl border border-slate-800">
              <div className="flex justify-between items-center mb-4">
                <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Piezoelectric Tile Array</span>
                <button 
                  onClick={simulateBassDrop}
                  disabled={!sensorsActive}
                  className={`px-3 py-1 rounded text-[9px] font-black uppercase tracking-widest transition border ${
                    !sensorsActive ? 'bg-slate-800 border-slate-700 text-slate-600 cursor-not-allowed' : 
                    'bg-rose-950/40 border-rose-900 text-rose-500 hover:bg-rose-900/60'
                  }`}
                >
                  Inject Bass Drop
                </button>
              </div>
              
              {/* Tile grid visualizer */}
              <div className="grid grid-cols-4 gap-1">
                {floorGrid.map((val, idx) => (
                  <div 
                    key={idx} 
                    className="h-8 rounded-[4px] transition-all duration-[50ms]"
                    style={{ 
                      backgroundColor: sensorsActive ? `rgba(234, 179, 8, ${val / 100})` : '#1e293b',
                      boxShadow: val > 80 ? '0 0 10px rgba(234, 179, 8, 0.8)' : 'none'
                    }}
                  ></div>
                ))}
              </div>
            </div>

          </div>
        </div>

      </div>
      
    </div>
  );
};

export default KineticEnergyHarvesting;
