/* eslint-disable */
import React, { useState, useEffect } from 'react';

const KineticEnergyFloor = () => {
  const [systemActive, setSystemActive] = useState(false);
  
  // Kinetic Metrics
  const [energyRate, setEnergyRate] = useState(0); // Joules per sec (Watts)
  const [totalEnergy, setTotalEnergy] = useState(14500); // Kilojoules generated total
  const [gridOffset, setGridOffset] = useState(0); // % of stage lighting powered
  
  const [sysLog, setSysLog] = useState([
    { id: 1, time: '17:00:00', type: 'SYS', msg: 'Piezoelectric Telemetry Grid Online.' },
    { id: 2, time: '17:00:02', type: 'SYS', msg: 'Syncing kinetic battery array to main stage DMX lights.' }
  ]);

  // Visualizer State
  const [tiles, setTiles] = useState(Array.from({ length: 64 }).map((_, i) => ({ id: i, active: false })));
  const [moshPit, setMoshPit] = useState(false);

  useEffect(() => {
    let loop;
    
    if (systemActive) {
      loop = setInterval(() => {
          
          // Randomly activate tiles to simulate dancing
          setTiles(prev => prev.map(t => {
              const chance = moshPit ? 0.4 : 0.05;
              if (Math.random() < chance) {
                  return { ...t, active: true, hue: 120 + Math.random() * 60 }; // Green/Cyan
              }
              return { ...t, active: false };
          }));

          // Calculate energy based on active tiles
          const activeCount = tiles.filter(t => t.active).length;
          const currentWatts = activeCount * (moshPit ? 45 : 25);
          
          setEnergyRate(currentWatts);
          setTotalEnergy(prev => prev + (currentWatts / 1000)); // Convert to kJ
          
          // Max stage lighting uses 50,000 Watts
          setGridOffset(Math.min(100, (currentWatts / 2000) * 100)); // Scaled down for demo

      }, 200); 
    }
    
    return () => { if (loop) clearInterval(loop); };
  }, [systemActive, moshPit, tiles]);

  const triggerMoshPit = () => {
      setMoshPit(true);
      addLog('ACTION', 'Massive kinetic spike detected! Crowd entered MOSH PIT state.');
      addLog('SUCCESS', 'Piezoelectric array operating at 140% nominal capacity.');
      
      setTimeout(() => {
          setMoshPit(false);
          if (systemActive) addLog('SYS', 'Crowd kinetic output returned to baseline.');
      }, 5000);
  };

  const toggleSystem = () => {
    if (!systemActive) {
      setSystemActive(true);
      addLog('SYS', 'Connecting piezoelectric dancefloor to Stage Main Breaker.');
    } else {
      setSystemActive(false);
      setEnergyRate(0);
      setGridOffset(0);
      setTiles(prev => prev.map(t => ({ ...t, active: false })));
      addLog('WARN', 'Kinetic Grid Offline. Stage reverting 100% to diesel generators.');
    }
  };

  const addLog = (type, msg) => {
    const now = new Date();
    const timeStr = `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}:${now.getSeconds().toString().padStart(2, '0')}.${Math.floor(Math.random()*999).toString().padStart(3,'0')}`;
    setSysLog(prev => [{ id: Date.now()+Math.random(), time: timeStr, type, msg }, ...prev].slice(0, 6));
  };

  return (
    <div className="min-h-screen bg-[#040806] flex items-center justify-center font-sans p-6 text-slate-300">
      
      <div className="max-w-7xl w-full grid grid-cols-1 lg:grid-cols-12 gap-8 items-start relative">
        
        {/* Left Side: Control Hub (Col span 7) */}
        <div className="lg:col-span-7 space-y-6">
          <div className="inline-block bg-emerald-900/40 text-emerald-400 border border-emerald-500/30 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-widest mb-2 flex items-center w-max">
            <span className="mr-2">⚡</span> Sustainability Tech
          </div>
          <h1 className="text-4xl md:text-5xl font-black text-white leading-tight">
            Real-Time Kinetic <br/><span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 via-green-500 to-lime-500">Energy Harvesting</span>.
          </h1>
          <p className="text-slate-400 text-sm leading-relaxed mb-6">
            Festivals consume massive amounts of diesel fuel for generators, leading to high carbon emissions and negative environmental PR. Eventra solves this by integrating piezoelectric kinetic dancefloors across the main stages. Eventra's platform hooks into the floor's API to track joules generated by the dancing crowd in real-time. This telemetry is fed directly into a gamified frontend UI projected on the stage's side screens, showing attendees exactly how much of the stage's lighting rig they are actively powering through their own physical movement.
          </p>

          <div className="bg-[#08120c] rounded-3xl p-6 border border-slate-800 shadow-xl relative overflow-hidden flex flex-col h-[400px]">
             
             <div className="flex justify-between items-center mb-6 border-b border-slate-800 pb-4">
               <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest flex items-center">
                 <span className="text-emerald-500 text-lg mr-2">🎛️</span> Piezoelectric Telemetry
               </h3>
               
               <div className="flex space-x-2">
                 <button 
                   onClick={toggleSystem}
                   className={`px-4 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest transition shadow-md flex items-center ${
                     systemActive ? 'bg-slate-800 text-slate-500 border border-slate-700' :
                     'bg-emerald-600 hover:bg-emerald-500 text-white shadow-[0_0_15px_rgba(16,185,129,0.4)]'
                   }`}
                 >
                   {systemActive ? 'Disconnect Grid' : 'Engage Floor Sensors'}
                 </button>
               </div>
             </div>

             <div className="grid grid-cols-3 gap-4 mb-6">
               
               {/* Current Power Generation */}
               <div className={`col-span-1 p-4 rounded-xl border flex flex-col justify-center relative overflow-hidden transition-all duration-300 ${
                 moshPit ? 'bg-lime-950/40 border-lime-500/50 shadow-[0_0_15px_rgba(132,204,22,0.3)] animate-pulse' :
                 systemActive ? 'bg-emerald-950/20 border-emerald-900/50' : 'bg-slate-900 border-slate-800'
               }`}>
                 <span className="text-[10px] text-slate-500 font-bold uppercase tracking-widest block mb-2 text-ellipsis overflow-hidden whitespace-nowrap">
                   Live Output
                 </span>
                 <div className="flex items-end">
                   <span className={`text-3xl font-black font-mono leading-none transition-colors duration-300 ${
                     moshPit ? 'text-lime-400' : 
                     systemActive ? 'text-emerald-400' : 'text-slate-600'
                   }`}>
                     {energyRate}
                   </span>
                   <span className="text-[10px] font-bold text-slate-500 ml-1 pb-1">Watts</span>
                 </div>
               </div>

               {/* Stage Grid Offset */}
               <div className={`col-span-1 p-4 rounded-xl border flex flex-col justify-center relative overflow-hidden transition-all duration-300 ${
                 gridOffset > 50 ? 'bg-cyan-950/40 border-cyan-500/50 shadow-[0_0_15px_rgba(6,182,212,0.3)]' :
                 systemActive ? 'bg-slate-900 border-slate-800' : 'bg-slate-900 border-slate-800'
               }`}>
                 <span className="text-[10px] text-slate-500 font-bold uppercase tracking-widest block mb-2 text-ellipsis overflow-hidden whitespace-nowrap">
                   Diesel Grid Offset
                 </span>
                 <div className="flex items-end">
                   <span className={`text-3xl font-black font-mono leading-none ${
                     gridOffset > 50 ? 'text-cyan-400' : 'text-slate-600'
                   }`}>
                     {gridOffset.toFixed(1)}
                   </span>
                   <span className="text-[10px] font-bold text-slate-500 ml-1 pb-1">%</span>
                 </div>
               </div>
               
               {/* Total Energy (Cumulative) */}
               <div className={`col-span-1 p-4 rounded-xl border flex flex-col justify-center relative overflow-hidden transition-all duration-300 ${
                 systemActive ? 'bg-slate-800/80 border-slate-700' : 'bg-slate-900 border-slate-800'
               }`}>
                 <span className="text-[10px] text-slate-500 font-bold uppercase tracking-widest block mb-2 text-ellipsis overflow-hidden whitespace-nowrap">
                   Cumulative KJs
                 </span>
                 <div className="flex items-end">
                   <span className={`text-2xl font-black font-mono leading-none ${
                     systemActive ? 'text-slate-300' : 'text-slate-600'
                   }`}>
                     {totalEnergy.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                   </span>
                 </div>
               </div>

             </div>

             {/* System Log */}
             <div className="flex-1 bg-[#020503] rounded-xl border border-slate-800 p-4 font-mono text-[10px] overflow-hidden relative flex flex-col shadow-inner mt-auto">
               <span className="text-slate-500 uppercase font-bold tracking-widest block mb-2 border-b border-slate-800 pb-2 flex justify-between">
                 <span>Grid Routing Ledger</span>
                 {moshPit && <span className="text-lime-400 font-black animate-pulse">SURGE CAPACITY ROUTED</span>}
               </span>
               
               <div className="flex-1 overflow-y-auto space-y-1.5 text-slate-400 pr-2">
                 {sysLog.map((log) => (
                   <div key={log.id} className="flex items-start animate-fade-in-up">
                     <span className="text-slate-600 mr-2 shrink-0">[{log.time}]</span>
                     <span className={
                       log.type === 'SUCCESS' ? 'text-emerald-400 font-bold' : 
                       log.type === 'CRIT' ? 'text-red-500 font-bold uppercase bg-red-900/30 px-1' :
                       log.type === 'WARN' ? 'text-orange-400 font-bold' :
                       log.type === 'ACTION' ? 'text-lime-400 font-bold' : 'text-slate-400'
                     }>{log.msg}</span>
                   </div>
                 ))}
               </div>
             </div>

          </div>
        </div>

        {/* Right Side: Visualizers (Col span 5) */}
        <div className="lg:col-span-5 flex justify-center pt-8 lg:pt-0">
          
          <div className="w-full max-w-[420px] flex flex-col items-center">
            
            {/* Gamification Visualizer */}
            <div className={`w-full rounded-[1.5rem] border-[4px] border-[#0f172a] shadow-[0_0_50px_rgba(0,0,0,0.8)] relative flex flex-col h-[400px] overflow-hidden font-sans mb-6 transition-colors duration-1000 ${
                !systemActive ? 'bg-slate-900' : 'bg-[#08120c]'
            }`}>
              
              <div className="absolute top-0 inset-x-0 p-3 text-center z-40 pointer-events-none flex justify-between bg-black/60 border-b border-white/5 backdrop-blur-md">
                <span className="text-[8px] font-black uppercase tracking-widest text-emerald-400">GAMIFICATION UI</span>
                <span className="text-[8px] font-mono text-slate-400">SIDE-STAGE PROJECTOR</span>
              </div>

              <div className="flex-1 relative flex flex-col items-center justify-between overflow-hidden px-6 pt-12 pb-6">
                  
                  {!systemActive ? (
                     <div className="absolute inset-0 flex items-center justify-center">
                         <span className="text-[10px] font-black text-slate-700 uppercase tracking-widest">PROJECTOR OFFLINE</span>
                     </div>
                  ) : (
                    <div className="w-full h-full relative z-20 flex flex-col justify-between">
                        
                        {/* Battery Level / Stage Lights */}
                        <div className="w-full flex justify-center mt-2">
                            <div className="flex space-x-4 items-center">
                                {/* DMX Lights */}
                                {[1, 2, 3].map(i => (
                                    <div key={i} className="flex flex-col items-center relative">
                                        <div className={`w-10 h-10 rounded-full bg-slate-900 border-2 transition-all duration-300 z-10 ${
                                            gridOffset > (i * 30) ? 'border-yellow-400 shadow-[0_0_20px_rgba(250,204,21,0.8)]' : 'border-slate-700'
                                        }`}>
                                            <div className={`absolute inset-1 rounded-full transition-all duration-300 ${
                                                gridOffset > (i * 30) ? 'bg-yellow-100' : 'bg-slate-800'
                                            }`}></div>
                                        </div>
                                        {/* Beam */}
                                        {gridOffset > (i * 30) && (
                                            <div className="absolute top-10 w-4 h-24 bg-yellow-400/20 blur-md origin-top"></div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>

                        <div className="w-full text-center mt-4">
                            <h2 className="text-xl font-black text-white uppercase tracking-widest">
                                Power The Stage!
                            </h2>
                            <div className="w-full h-4 bg-slate-800 rounded-full mt-2 overflow-hidden border border-slate-700">
                                <div 
                                    className="h-full bg-gradient-to-r from-emerald-500 to-lime-400 transition-all duration-300"
                                    style={{ width: `${gridOffset}%` }}
                                ></div>
                            </div>
                        </div>

                        {/* Kinetic Grid Floor */}
                        <div className="w-full mt-8 perspective-1000">
                            <div className="grid grid-cols-8 gap-1 transform rotate-x-45 scale-125">
                                {tiles.map(t => (
                                    <div 
                                        key={t.id}
                                        className={`w-full aspect-square rounded-sm border transition-all duration-150 ${
                                            t.active 
                                              ? 'border-emerald-300 shadow-[0_0_15px_rgba(52,211,153,0.8)] z-10 scale-95' 
                                              : 'border-slate-800 bg-slate-900/50 z-0'
                                        }`}
                                        style={{
                                            backgroundColor: t.active ? `hsl(${t.hue}, 80%, 40%)` : '',
                                        }}
                                    ></div>
                                ))}
                            </div>
                            <div className="w-full text-center mt-8">
                                <span className="text-[10px] font-black uppercase tracking-widest text-emerald-500/50">Piezoelectric Array Sensor Data</span>
                            </div>
                        </div>

                    </div>
                  )}
                
              </div>
            </div>

            {/* Triggers */}
            <div className="w-full bg-[#08120c] p-4 rounded-xl border border-slate-800">
               <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest block mb-3 text-center">Simulate Crowd Energy</span>
               
               <div className="grid grid-cols-1 gap-2">
                 <button 
                   onClick={triggerMoshPit}
                   disabled={!systemActive || moshPit}
                   className={`w-full py-4 rounded-lg font-black uppercase tracking-widest text-[10px] transition border flex items-center justify-center ${
                     !systemActive || moshPit ? 'bg-slate-900 border-slate-800 text-slate-700 cursor-not-allowed' : 
                     'bg-lime-950/40 border-lime-600 text-lime-400 hover:bg-lime-900/60 shadow-[0_0_15px_rgba(132,204,22,0.3)] animate-pulse'
                   }`}
                 >
                   🎸 Open The Mosh Pit!
                 </button>
               </div>
            </div>

          </div>
        </div>

      </div>
      
    </div>
  );
};

export default KineticEnergyFloor;
