export const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  OWNER: 'OWNER',
  ORGANIZER: 'ORGANIZER',
  MODERATOR: 'MODERATOR',
  VOLUNTEER: 'VOLUNTEER',
  ATTENDEE: 'ATTENDEE',
});

export const PERMISSIONS = Object.freeze({
  CREATE_EVENT: 'CREATE_EVENT',
  EDIT_EVENT: 'EDIT_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  HOST_HACKATHON: 'HOST_HACKATHON',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  MODERATE_CONTENT: 'MODERATE_CONTENT',
  MANAGE_CHECKINS: 'MANAGE_CHECKINS',
  MANAGE_EVENT_ROLES: 'MANAGE_EVENT_ROLES',
  EDIT_USER: 'EDIT_USER',
  DELETE_USER: 'DELETE_USER',
});

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.freeze(Object.values(PERMISSIONS)),
  [ROLES.ADMIN]: Object.freeze([
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.EDIT_EVENT,
    PERMISSIONS.DELETE_EVENT,
    PERMISSIONS.HOST_HACKATHON,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.EDIT_USER,    // ← added: ADMIN with MANAGE_USERS must be able to edit users
    PERMISSIONS.DELETE_USER,  // ← added: ADMIN with MANAGE_USERS must be able to delete users
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MODERATE_CONTENT,
    PERMISSIONS.MANAGE_CHECKINS,
    PERMISSIONS.MANAGE_EVENT_ROLES,
  ]),
  [ROLES.OWNER]: Object.freeze([
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.EDIT_EVENT,
    PERMISSIONS.DELETE_EVENT,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MODERATE_CONTENT,
    PERMISSIONS.MANAGE_CHECKINS,
    PERMISSIONS.MANAGE_EVENT_ROLES,
  ]),
  [ROLES.ORGANIZER]: Object.freeze([
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.EDIT_EVENT,
    PERMISSIONS.HOST_HACKATHON,
    PERMISSIONS.VIEW_ANALYTICS,
  ]),
  [ROLES.MODERATOR]: Object.freeze([
    PERMISSIONS.MODERATE_CONTENT,
    PERMISSIONS.MANAGE_CHECKINS,
  ]),
  [ROLES.VOLUNTEER]: Object.freeze([
    PERMISSIONS.MODERATE_CONTENT,
    PERMISSIONS.MANAGE_CHECKINS,
  ]),
  [ROLES.ATTENDEE]: Object.freeze([]),
});
