/**
 * OfflineConflictModal
 *
 * Full-featured interactive modal that allows the user to reconcile conflicts
 * between locally-queued (offline) actions and the current server state.
 *
 * Feature set
 * ───────────
 *  - Powered by `useOfflineConflictState` so it automatically dequeues and
 *    displays conflicts as they arrive from the sync engine.
 *  - Shows a field-level diff report generated by `reconcileState()` so the
 *    user can see exactly which fields differ between local and server.
 *  - Three resolution strategies per field: keep local, keep server, or enter
 *    a custom override value.
 *  - "Bulk resolve" actions (keep all local / keep all server) for power users.
 *  - "Skip" button to move the current conflict to the back of the queue.
 *  - Live merged-payload preview panel so users can verify their choices.
 *  - Countdown timer shows the auto-dismiss deadline (60 s → server wins).
 *  - Queue-position badge ("Conflict 1 of 3") when multiple conflicts are pending.
 *  - Screen-reader accessible: ARIA live regions for announcements, role="dialog",
 *    focus trap via `useFocusTrap`, Escape key → server resolution.
 *  - Reduced-motion aware: respects prefers-reduced-motion for animations.
 *
 * @module OfflineConflictModal
 */

import React, { useState, useEffect, useRef, useCallback } from 'react';
import {
  AlertTriangle,
  Server,
  Save,
  X,
  Edit3,
  Check,
  RefreshCw,
  ChevronRight,
  Clock,
  Layers,
  Zap,
  SkipForward,
} from 'lucide-react';
import './OfflineConflictModal.css';
import { useFocusTrap } from '../../hooks/useFocusTrap';
import useOfflineConflictState, { RESOLUTION_STRATEGY } from '../../hooks/useOfflineConflictState';

// ─── CountdownBar ──────────────────────────────────────────────────────────────

/**
 * Animated countdown progress bar.
 *
 * @param {{ totalMs: number, onExpire: () => void }} props
 */
const CountdownBar = ({ totalMs, onExpire }) => {
  const [remaining, setRemaining] = useState(totalMs);
  const startRef   = useRef(Date.now());
  const expiredRef = useRef(false);

  useEffect(() => {
    startRef.current  = Date.now();
    expiredRef.current = false;
    setRemaining(totalMs);

    const tick = () => {
      const elapsed = Date.now() - startRef.current;
      const left    = Math.max(0, totalMs - elapsed);
      setRemaining(left);
      if (left === 0 && !expiredRef.current) {
        expiredRef.current = true;
        onExpire?.();
      }
    };

    const id = setInterval(tick, 250);
    return () => clearInterval(id);
  }, [totalMs, onExpire]);

  const pct      = (remaining / totalMs) * 100;
  const secs     = Math.ceil(remaining / 1_000);
  const isUrgent = remaining < totalMs * 0.3; // last 30 %

  return (
    <div className="ocm-countdown-wrapper" aria-label={`Auto-dismisses in ${secs} seconds`}>
      <div className="ocm-countdown-label">
        <Clock size={11} aria-hidden="true" />
        <span>Auto-dismiss in <strong>{secs}s</strong> — server version will be kept</span>
      </div>
      <div className="ocm-countdown-track">
        <div
          className={`ocm-countdown-fill ${isUrgent ? 'urgent' : ''}`}
          style={{ width: `${pct}%` }}
          role="progressbar"
          aria-valuenow={secs}
          aria-valuemin={0}
          aria-valuemax={Math.ceil(totalMs / 1_000)}
        />
      </div>
    </div>
  );
};

// ─── FieldDiffRow ─────────────────────────────────────────────────────────────

/**
 * Renders a single field comparison row with three-way resolution toggle.
 */
const FieldDiffRow = ({ fieldKey, localVal, serverVal, selection, customVal, onSelect, onCustomChange }) => {
  const label = fieldKey.replace(/([A-Z])/g, ' $1').trim();

  return (
    <div className="ocm-diff-row ocm-diff-changed">
      <div className="ocm-diff-field-label" title={fieldKey}>{label}</div>

      <div className="ocm-option-grid">
        {/* Keep Local */}
        <button
          type="button"
          role="radio"
          aria-checked={selection === RESOLUTION_STRATEGY.LOCAL}
          aria-label={`Keep local value for ${label}: ${localVal}`}
          onClick={() => onSelect(fieldKey, RESOLUTION_STRATEGY.LOCAL)}
          className={`ocm-option-btn ${selection === RESOLUTION_STRATEGY.LOCAL ? 'active local' : ''}`}
        >
          <div className="ocm-option-header text-indigo-400">
            <Edit3 size={11} aria-hidden="true" className="inline mr-1" />
            Client (Offline)
          </div>
          <div className="ocm-option-val">{localVal}</div>
        </button>

        {/* Keep Server */}
        <button
          type="button"
          role="radio"
          aria-checked={selection === RESOLUTION_STRATEGY.SERVER}
          aria-label={`Keep server value for ${label}: ${serverVal}`}
          onClick={() => onSelect(fieldKey, RESOLUTION_STRATEGY.SERVER)}
          className={`ocm-option-btn ${selection === RESOLUTION_STRATEGY.SERVER ? 'active server' : ''}`}
        >
          <div className="ocm-option-header text-rose-400">
            <Server size={11} aria-hidden="true" className="inline mr-1" />
            Server (Remote)
          </div>
          <div className="ocm-option-val">{serverVal}</div>
        </button>

        {/* Custom Override */}
        <button
          type="button"
          role="radio"
          aria-checked={selection === 'custom'}
          aria-label={`Enter custom value for ${label}`}
          onClick={() => onSelect(fieldKey, 'custom')}
          className={`ocm-option-btn ${selection === 'custom' ? 'active custom' : ''}`}
        >
          <div className="ocm-option-header text-amber-400">
            <RefreshCw size={11} aria-hidden="true" className="inline mr-1" />
            Custom Override
          </div>
          <div className="ocm-option-val">
            {selection === 'custom' ? 'Editing…' : 'Enter custom value'}
          </div>
        </button>
      </div>

      {selection === 'custom' && (
        <div className="ocm-custom-input-container mt-3 animate-fade-in">
          <label htmlFor={`custom-input-${fieldKey}`} className="sr-only">
            Custom value for {label}
          </label>
          <input
            id={`custom-input-${fieldKey}`}
            type="text"
            value={customVal}
            onChange={(e) => onCustomChange(fieldKey, e.target.value)}
            placeholder="Type custom resolved value…"
            className="ocm-custom-input"
            autoFocus
          />
        </div>
      )}
    </div>
  );
};

// ─── Main Component ───────────────────────────────────────────────────────────

export default function OfflineConflictModal() {
  const {
    activeConflict,
    pendingCount,
    resolvedCount,
    resolveActive,
    skipActive,
    resolveAll,
  } = useOfflineConflictState();

  // Per-field resolution selections: { [fieldKey]: 'local' | 'server' | 'custom' }
  const [selections, setSelections]   = useState({});
  // Per-field custom override values: { [fieldKey]: string }
  const [customValues, setCustomValues] = useState({});

  const trapRef     = useFocusTrap(!!activeConflict);
  const announceRef = useRef(null);

  // ── Re-initialize per-field state whenever a new conflict becomes active ──
  useEffect(() => {
    if (!activeConflict) return;

    const { item, serverState } = activeConflict;
    const localPayload  = item?.payload  || {};
    const serverPayload = serverState    || {};

    const allKeys = Array.from(
      new Set([...Object.keys(localPayload), ...Object.keys(serverPayload)])
    ).filter(
      (k) => !['id', 'userId', 'eventId', 'timestamp', 'version', 'forceOverride', 'clientTimestamp', 'serverTimestamp'].includes(k)
    );

    const initSel = {};
    const initCus = {};
    allKeys.forEach((k) => {
      initSel[k] = RESOLUTION_STRATEGY.LOCAL;
      initCus[k] = String(localPayload[k] !== undefined ? localPayload[k] : '');
    });

    setSelections(initSel);
    setCustomValues(initCus);

    if (announceRef.current) {
      announceRef.current.textContent =
        `Offline synchronization conflict detected for item ${item.id}. ` +
        `${(activeConflict.report?.conflicts?.length ?? 0)} field(s) differ. Modal opened.`;
    }
  }, [activeConflict?.id]); // only re-init when the active conflict's ID changes

  // ── Keyboard: Escape → keep server version ────────────────────────────────
  useEffect(() => {
    if (!activeConflict) return;
    const onKeyDown = (e) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        handleQuickResolve(RESOLUTION_STRATEGY.SERVER);
      }
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [activeConflict]); // eslint-disable-line react-hooks/exhaustive-deps

  if (!activeConflict) return null;

  const { item, serverState, report, receivedAt } = activeConflict;
  const localPayload  = item?.payload  || {};
  const serverPayload = serverState    || {};

  const allKeys = Array.from(
    new Set([...Object.keys(localPayload), ...Object.keys(serverPayload)])
  ).filter(
    (k) => !['id', 'userId', 'eventId', 'timestamp', 'version', 'forceOverride', 'clientTimestamp', 'serverTimestamp'].includes(k)
  );

  // ── Build the merged payload from current per-field selections ────────────
  const getMergedPayload = () => {
    const result = { ...serverPayload };
    allKeys.forEach((k) => {
      if (selections[k] === RESOLUTION_STRATEGY.LOCAL) {
        result[k] = localPayload[k];
      } else if (selections[k] === RESOLUTION_STRATEGY.SERVER) {
        result[k] = serverPayload[k];
      } else if (selections[k] === 'custom') {
        result[k] = customValues[k];
      }
    });
    return result;
  };

  const mergedPayload = getMergedPayload();

  // ── Resolution handlers ───────────────────────────────────────────────────
  const handleQuickResolve = (strategy) => {
    resolveActive(strategy, strategy === RESOLUTION_STRATEGY.MERGE ? mergedPayload : undefined);
    if (announceRef.current) {
      announceRef.current.textContent = `Conflict resolved: ${strategy} version applied.`;
    }
  };

  const handleMergeResolve = () => {
    resolveActive(RESOLUTION_STRATEGY.MERGE, mergedPayload);
    if (announceRef.current) {
      announceRef.current.textContent = 'Conflict resolved: merged payload submitted.';
    }
  };

  const handleSelectionChange = (key, type) => {
    setSelections((prev) => ({ ...prev, [key]: type }));
    if (announceRef.current) {
      announceRef.current.textContent = `Selected ${type} value for ${key}.`;
    }
  };

  const handleCustomValueChange = (key, value) => {
    setCustomValues((prev) => ({ ...prev, [key]: value }));
  };

  const handleCountdownExpire = () => {
    // Auto-dismiss to server on timer expiry (useOfflineSync handles this too
    // on its own timer, but we close the modal UI immediately here)
    handleQuickResolve(RESOLUTION_STRATEGY.SERVER);
  };

  const conflictFieldCount = report?.conflicts?.length ?? allKeys.length;
  const localVersion       = report?.localVersion  ?? '—';
  const serverVersion      = report?.serverVersion ?? '—';
  const localTimestamp     = report?.localTimestamp  ? new Date(report.localTimestamp).toLocaleTimeString()  : '—';
  const serverTimestamp    = report?.serverTimestamp ? new Date(report.serverTimestamp).toLocaleTimeString() : '—';
  const timeoutMs          = activeConflict.item?.timeoutMs ?? 60_000;

  // How many seconds ago did we receive this conflict?
  const receivedSecsAgo    = Math.floor((Date.now() - receivedAt) / 1_000);

  return (
    <div className="ocm-modal-overlay" role="presentation">
      {/* Screen reader announcements */}
      <div ref={announceRef} className="sr-only" aria-live="assertive" aria-atomic="true" />

      <div
        ref={trapRef}
        className="ocm-modal-container"
        role="dialog"
        aria-modal="true"
        aria-labelledby="ocm-title"
        aria-describedby="ocm-desc"
        tabIndex={-1}
      >
        {/* ── Header ─────────────────────────────────────────────────────── */}
        <div className="ocm-header">
          <div className="ocm-header-left">
            <div className="ocm-warning-icon" aria-hidden="true">
              <AlertTriangle size={18} />
            </div>
            <div>
              <h2 id="ocm-title" className="ocm-title">Offline Sync Conflict</h2>
              <p id="ocm-desc" className="ocm-subtitle">
                The server state changed while you were offline.
                Choose which version to keep for each field.
              </p>
            </div>
          </div>

          <div className="ocm-header-right">
            {/* Queue position badge */}
            {pendingCount > 1 && (
              <div className="ocm-queue-badge" aria-label={`Conflict 1 of ${pendingCount}`}>
                <Layers size={11} aria-hidden="true" />
                <span>1 of {pendingCount}</span>
              </div>
            )}

            <button
              onClick={() => handleQuickResolve(RESOLUTION_STRATEGY.SERVER)}
              aria-label="Dismiss — keep server version"
              className="ocm-close-btn"
            >
              <X size={16} aria-hidden="true" />
            </button>
          </div>
        </div>

        {/* ── Meta strip ──────────────────────────────────────────────────── */}
        <div className="ocm-meta-strip">
          <span className="ocm-meta-chip">
            <Zap size={10} aria-hidden="true" />
            {conflictFieldCount} field{conflictFieldCount !== 1 ? 's' : ''} differ
          </span>
          <span className="ocm-meta-chip">
            Local v{localVersion}
            <ChevronRight size={10} aria-hidden="true" className="mx-0.5" />
            Server v{serverVersion}
          </span>
          <span className="ocm-meta-chip">
            <Clock size={10} aria-hidden="true" />
            Local: {localTimestamp}
          </span>
          <span className="ocm-meta-chip">
            <Server size={10} aria-hidden="true" />
            Server: {serverTimestamp}
          </span>
          {resolvedCount > 0 && (
            <span className="ocm-meta-chip resolved">
              <Check size={10} aria-hidden="true" />
              {resolvedCount} resolved this session
            </span>
          )}
        </div>

        {/* ── Countdown ───────────────────────────────────────────────────── */}
        <div className="ocm-countdown-section">
          <CountdownBar
            totalMs={Math.max(0, timeoutMs - receivedSecsAgo * 1_000)}
            onExpire={handleCountdownExpire}
          />
        </div>

        {/* ── Body: field diff list ────────────────────────────────────────── */}
        <div className="ocm-body">
          {allKeys.length === 0 ? (
            <div className="ocm-no-fields">
              <Check size={18} className="text-emerald-400 mb-2" aria-hidden="true" />
              <p>No differing fields detected.</p>
              <p className="ocm-no-fields-sub">The server may have bumped only the version number.</p>
            </div>
          ) : (
            <div className="ocm-diff-list">
              {allKeys.map((key) => (
                <FieldDiffRow
                  key={key}
                  fieldKey={key}
                  localVal={localPayload[key] !== undefined ? String(localPayload[key]) : '—'}
                  serverVal={serverPayload[key] !== undefined ? String(serverPayload[key]) : '—'}
                  selection={selections[key] ?? RESOLUTION_STRATEGY.LOCAL}
                  customVal={customValues[key] ?? ''}
                  onSelect={handleSelectionChange}
                  onCustomChange={handleCustomValueChange}
                />
              ))}
            </div>
          )}

          {/* ── Live preview panel ─────────────────────────────────────────── */}
          <div className="ocm-preview-panel" aria-label="Merged payload preview">
            <div className="ocm-preview-header">
              <Check size={12} className="text-emerald-400 mr-1.5" aria-hidden="true" />
              <span className="ocm-preview-label">Live Reconciliation Preview</span>
            </div>
            <pre className="ocm-preview-content" role="region" aria-label="Merged payload JSON">
              {JSON.stringify(mergedPayload, null, 2)}
            </pre>
          </div>
        </div>

        {/* ── Footer ──────────────────────────────────────────────────────── */}
        <div className="ocm-footer">
          {/* Bulk / skip actions */}
          <div className="ocm-footer-secondary">
            {pendingCount > 1 && (
              <>
                <button
                  type="button"
                  className="ocm-btn ocm-btn-ghost"
                  onClick={() => resolveAll(RESOLUTION_STRATEGY.SERVER)}
                  title="Resolve all pending conflicts by keeping server state"
                >
                  Keep server for all
                </button>
                <button
                  type="button"
                  className="ocm-btn ocm-btn-ghost"
                  onClick={skipActive}
                  title="Skip this conflict and move to the next one"
                >
                  <SkipForward size={13} aria-hidden="true" className="mr-1" />
                  Skip
                </button>
              </>
            )}
          </div>

          {/* Primary actions */}
          <div className="ocm-footer-primary">
            <button
              type="button"
              className="ocm-btn ocm-btn-secondary"
              onClick={() => handleQuickResolve(RESOLUTION_STRATEGY.SERVER)}
              aria-label="Discard local changes — keep server version"
            >
              <Server size={13} aria-hidden="true" className="mr-1.5" />
              Keep Server
            </button>

            <button
              type="button"
              className="ocm-btn ocm-btn-primary"
              onClick={() => handleQuickResolve(RESOLUTION_STRATEGY.LOCAL)}
              aria-label="Overwrite server — keep local (offline) version"
            >
              <Save size={13} aria-hidden="true" className="mr-1.5" />
              Keep Local
            </button>

            <button
              type="button"
              className="ocm-btn ocm-btn-accent"
              onClick={handleMergeResolve}
              aria-label="Submit field-merged resolution"
            >
              <Check size={13} aria-hidden="true" className="mr-1.5" />
              Submit Merge
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
