name: Prettier Code Formatter

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,jsx,ts,tsx,css,json,md}
          commit_message: "chore: apply prettier formatting"
          github_token: ${{ secrets.GITHUB_TOKEN }}
